// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tacos;

namespace Tacos.Migrations
{
    [DbContext(typeof(TacosContext))]
    [Migration("20211207103146_addComposition")]
    partial class addComposition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Tacos.Composition", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("TacosId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "TacosId");

                    b.HasIndex("TacosId");

                    b.ToTable("Composition");
                });

            modelBuilder.Entity("Tacos.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ingredient");
                });

            modelBuilder.Entity("Tacos.Tacos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Tacos");
                });

            modelBuilder.Entity("Tacos.Composition", b =>
                {
                    b.HasOne("Tacos.Ingredient", "Ingredient")
                        .WithMany("Tacos")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tacos.Tacos", "Tacos")
                        .WithMany("Ingredients")
                        .HasForeignKey("TacosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Tacos");
                });

            modelBuilder.Entity("Tacos.Ingredient", b =>
                {
                    b.Navigation("Tacos");
                });

            modelBuilder.Entity("Tacos.Tacos", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
